---
- hosts: all
  vars:
    scheduling_strategy: "{{ 'TIMER_DRIVEN' if SchedulingStrategy == 'EVENT_DRIVEN' else SchedulingStrategy }}"
    scheduling_period_timer_driven: "{{ '0 sec' if SchedulingStrategy == 'EVENT_DRIVEN' else SchedulingPeriodTimer }}"
    scheduling_period: "{{ SchedulingPeriodCron if SchedulingStrategy == 'CRON_DRIVEN' else scheduling_period_timer_driven }}"
  tasks:
    - name: Retrieve process group processors info
      ansible.builtin.uri:
        method: GET
        url: "{{ NIFI_API_ENDPOINT }}/process-groups/{{ pipeline_id }}/processors"
        validate_certs: "{{ NIFI_API_VALIDATE_CERTS }}"
        follow_redirects: safe
        return_content: yes
        headers:
          Authorization: "Bearer {{ NIFI_API_ACCESS_TOKEN }}"
      register: process_group_info_response

    - name: Extract info from the process group response
      ansible.builtin.set_fact:
        process_group_info: "{{ process_group_info_response.json }}"

    - name: Extract processor id from GenerateFlowFile, EvaluateJsonPath and UpdateAttribute processors
      ansible.builtin.set_fact:
        gen_flow_file_processor_id: "{{ process_group_info | json_query(gen_flow_file_query) | first }}"
        eval_json_path_processor_id: "{{ process_group_info | json_query(eval_json_path_query) | first }}"
        update_attr_processor_id: "{{ process_group_info | json_query(update_attr_query) | first }}"
      vars:
        gen_flow_file_query: "processors[?component.name=='GenerateFlowFile'].id"
        eval_json_path_query: "processors[?component.name=='EvaluateJsonPath'].id"
        update_attr_query: "processors[?component.name=='UpdateAttribute'].id"

    - name: Configure GenerateFlowFile Processor within the process group
      ansible.builtin.uri:
        method: PUT
        url: "{{ NIFI_API_ENDPOINT }}/processors/{{ gen_flow_file_processor_id }}"
        validate_certs: "{{ NIFI_API_VALIDATE_CERTS }}"
        return_content: no
        headers:
          Authorization: "Bearer {{ NIFI_API_ACCESS_TOKEN }}"
        body_format: json
        body:
          revision:
            version: 0
          component:
            id: "{{ gen_flow_file_processor_id }}"
            config:
              properties: 
                generate-ff-custom-text: "{{ List | to_json }}"
              schedulingStrategy: "{{ ListHTTPSchedulingStrategy }}"
              schedulingPeriod: "{{ ListHTTPSchedulingPeriodTimer }}"
        status_code: 200

    - name: Configure EvaluateJsonPath Processor within the process group
      ansible.builtin.uri:
        method: PUT
        url: "{{ NIFI_API_ENDPOINT }}/processors/{{ eval_json_path_processor_id }}"
        validate_certs: "{{ NIFI_API_VALIDATE_CERTS }}"
        return_content: no
        headers:
          Authorization: "Bearer {{ NIFI_API_ACCESS_TOKEN }}"
        body_format: json
        body:
          revision:
            version: 0
          component:
            id: "{{ eval_json_path_processor_id }}"
            config:
              properties: "{{ AttributeMap }}"
              schedulingStrategy: "{{ scheduling_strategy }}"
              schedulingPeriod: "{{ scheduling_period }}"
        status_code: 200

    - name: Configure UpdateAttribute Processor within the process group
      ansible.builtin.uri:
        method: PUT
        url: "{{ NIFI_API_ENDPOINT }}/processors/{{ update_attr_processor_id }}"
        validate_certs: "{{ NIFI_API_VALIDATE_CERTS }}"
        return_content: no
        headers:
          Authorization: "Bearer {{ NIFI_API_ACCESS_TOKEN }}"
        body_format: json
        body:
          revision:
            version: 0
          component:
            id: "{{ update_attr_processor_id }}"
            config:
              properties: 
                filename: "{{ Filename }}"
              schedulingStrategy: "{{ scheduling_strategy }}"
              schedulingPeriod: "{{ scheduling_period }}"
        status_code: 200