---
- name: Call HPC Exporter API to create a slurm collector
  uri: 
    url: http://{{hpc_exporter_address}}/collector
    method: post
    body: 
      scheduler: {{ "pbs" if (scheduler == "torque") else scheduler }}
      host: {{ ssh_host }}
      deployment_label: {{ deployment_label }}
      monitoring_id: {{ monitoring_id }}
      hpc_label: {{ ssh_host if (hpc_label == "") else hpc_label }}
      scrape_interval: {{ scrape_interval }}
    status_code: 200
    body_format: json
    headers:
      authorization: "Bearer {{ jwt }}"
  when: scheduler != "batch"