---
- hosts: all
  gather_facts: yes
  tasks:
  - name: Call HPC Exporter API to create a collector
    uri: 
      url: "{{hpc_exporter_address}}/collector"
      method: post
      body: 
        scheduler: "{{ (scheduler == 'torque') | ternary('pbs', scheduler) }}"
        host: "{{ ssh_host }}"
        deployment_label: "{{ deployment_label }}"
        monitoring_id: "{{ monitoring_id }}"
        hpc_label: "{{ ssh_host if (hpc_label == '') else hpc_label }}"
        scrape_interval: "{{ scrape_interval }}"
      status_code: 200
      body_format: json
      headers:
        Authorization: "Bearer {{ jwt }}"
    when: scheduler != "batch"