- hosts: all
  become_user: root
  become: yes
  vars:
    project_home: "{{ lookup('env', 'HOME') }}"
    image_path: "{{ image_name }}"
  tasks:  

  - set_fact:
      image_path: "{{ registry_url }}/{{ image_name }}"
    when: registry_url is defined

  - name: "Launch {{ alias}} container and connect to network"
    docker_container:
      name: "{{ alias }}"
      hostname: "{{ hostname | default(omit) }}"
      image: "{{ image_path }}" 
      restart_policy: "{{ restart_policy | default(omit) }}"
      detach: "{{ detach | default(omit) }}"      
      pull: true
      auto_remove: no
      command: 
        "{{ command }}"
      volumes:
        "{{ volumes }}"
      env:
        "{{ env }}"
      ports:
         "{{ ports }}"
      exposed_ports:
        "{{ exposed_ports }}"
      networks:
        - name: "{{ docker_network_name }}"        
          aliases:
            - "{{ alias }}"        
    notify:
      - "{{ alias }} sleep"
    when: docker_network_name != None    

  - name: "Launch {{ alias}} container"
    docker_container:
      name: "{{ alias }}"
      hostname: "{{ hostname | default(omit) }}"
      image: "{{ image_path }}" 
      restart_policy: "{{ restart_policy | default(omit) }}"
      detach: "{{ detach | default(omit) }}"      
      pull: true
      auto_remove: no
      command: 
        "{{ command }}"
      volumes:
        "{{ volumes }}"
      env:
        "{{ env }}"
      ports:
         "{{ ports }}"
      exposed_ports:
        "{{ exposed_ports }}"
    notify:
      - "{{ alias }} sleep"
    when: docker_network_name == None     

  handlers:  
  - name: "{{ alias }} sleep"
    command:
      sleep "{{ sleep }}"
    when: 
    - sleep > 0     
    
 
