---
- hosts: all
  become_user: root
  become: yes

  vars:
    pip_install_packages:
      - name: docker
    docker_package: "docker-ce-19.03.5-3.el7"

  pre_tasks:
    - name: update cache
      package:
        update_cache: yes

  tasks:
    - name: Set attributes
      set_stats:
        data:
          public_address: "{{ host_public_address }}"
    - name: Configure the docker mtu for OpenStack and restart docker host
      block:
        - lineinfile:
            path: /etc/docker/daemon.json
            line: "{\"mtu\": 1450}"
            create: yes
        - service:
            name: docker
            state: restarted

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_distribution == "CentOS"
    - role: geerlingguy.pip
    - role: geerlingguy.docker